### ISSUE TITLE
Confusing connection handling log after controller reconnection

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/jul#11]
e.g. if the rsb-openhab-binding is not available in openhab and bco is starting and trys to connect to the openhab rsb controller this message is printed after binding start:
<pre>
17:56:02.775 [pool-1-thread-23] WARN  o.o.b.m.a.b.o.AgentBindingOpenHABImpl$2 Controller[/openhab/] does not respond!  Next retry timeout in 30 sec.
17:56:02.781 [pool-1-thread-23] INFO  o.o.b.m.a.b.o.AgentBindingOpenHABImpl$2 Got response from Controller[/openhab/] and continue processing.
</pre>
So the log says that openhab does not response and afterwards the  response is directly confirmed. Is this just a log bug?

**Comment by pLeminoq** [comment]
Commit 6dba72e84e6fda8cc248a1a1c8f757bfb96fbfcd played also in important role because it fixed an issue where remotes would automatically reconnect on connection loss.
