### ISSUE TITLE
DeviceRegistry not synchronized yet in registry: UnitGroupPlacementConfigConsistencyHandler

### ISSUE THREAD

**Issue by THuppke** [openbase/jul#35]
After the merging commit  a4dd66d the DeviceRegistry is no longer available in the early state of the startup of bco-registry. Specifically in the UnitGroupPlacementConfigConsistencyHandler the shape of the unit groups can not be calculated correctly during the startup of bco-registry because the information of the corresponding devices is not ready. 

I noticed this in bco-stage where wrong bounding boxes appeared. To trace the error you can add 
`                ExceptionPrinter.printHistory(ex, logger, LogLevel.ERROR);`
to `getPointsToCheck` of `UnitGroupPlacementConfigConsistencyHandler` between line 242 and 243.
This will lead to the repeated following output on starting bco-registry: 

11:40:31.388 [pool-1-thread-1] ERROR o.o.b.r.u.c.c.u.UnitGroupPlacementConfigConsistencyHandler ═╦═⚀ Shape[of Unit [LLamp3]]] is not available!
11:40:31.388 [pool-1-thread-1] ERROR o.o.b.r.u.c.c.u.UnitGroupPlacementConfigConsistencyHandler  ╚══╦═⚀ Shape[of unit ec06d7c5-0852-4912-94ff-3d85e51a39c7]] is not available!
11:40:31.388 [pool-1-thread-1] ERROR o.o.b.r.u.c.c.u.UnitGroupPlacementConfigConsistencyHandler     ╚══╦═⚀ Shape[of Unit [LLamp3]]] is not available!
11:40:31.388 [pool-1-thread-1] ERROR o.o.b.r.u.c.c.u.UnitGroupPlacementConfigConsistencyHandler        ╚══╦═⚀ DeviceRegistryRemote[scope:/registry/device/] not synchronized yet!
11:40:31.388 [pool-1-thread-1] ERROR o.o.b.r.u.c.c.u.UnitGroupPlacementConfigConsistencyHandler           ╚════⚀ Context[data] is not available!
11:40:31.388 [pool-1-thread-1] ERROR o.o.b.r.u.c.c.u.UnitGroupPlacementConfigConsistencyHandler =====================================

**Comment by pLeminoq** [comment]
Should be fixed by commit openbase/bco.registry@b3d99f7a344d63a9dcf31253f6ec1d5bc7892671.
