### ISSUE TITLE
All Registries do not work in read only mode

### ISSUE THREAD

**Issue by pLeminoq** [openbase/jul#41]
I started bco in read only mode and a lot of exceptions were printed because entries could not be registered. The reason for this is that all managers like the device manager use registries to maintain unit controller. But in read only mode no entries can be written to these registries because the check for read only mode is done in the AbstractRegistry.
I removed the check for read only and force mode in commit :

* f99b56f8a4f55afb9e9b48988b4c85de71ec3223 

from the AbstractRegistry in placed them in the FileSynchronziedRegistry because I think they only make sense for registries working with the file system.

**Comment by DivineThreepwood** [comment]
Issue is outdated.
