### ISSUE TITLE
Performance problems with authenticated requests

### ISSUE THREAD

**Issue by pLeminoq** [openbase/jul#49]
The timeout for a request data is 500 ms. When it does not return it will be increased and called again. This is a problem with authenticated requests because the controller does not just transfer its data object but filters it for the user. This can take up to 1.5 seconds for the unit registry with the CSRA database on my laptop. 
This means that the remote unnecessarily cancels the request and performs a new one. Even more delay is caused by the fact that RPCs are not cancelled on controller side which means that the controller finishes the request before working on a new one. This problem gets even worse if more than one remote request authenticated data from the controller.
So there are 2 things that have to be done to fix this completely:

* The timeout on remote side has to be increased and the ping method has to be used to verify that the controller is still available.
* RPCs should be non blocking in this case.

**Comment by pLeminoq** [comment]
The first part has been implemented in commit b535c4418b0ded791cfd773d31544df24a07eff0. Currently only on a feature branch.

**Comment by DivineThreepwood** [comment]
This is a performance issue and not a part of the initial 2.0 release.

**Comment by DivineThreepwood** [comment]
Has been solved anyway by non blocking rpc calls and improving unit lookup speed.
